general {
    before_sleep_cmd = qs ipc call lock lock && solaar config "MX Mechanical Mini" backlight Disabled
    unlock_cmd = solaar config "MX Mechanical Mini" backlight Enabled
}

listener {
    timeout = 300
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })' && solaar config "MX Mechanical Mini" backlight Disabled
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && solaar config "MX Mechanical Mini" backlight Enabled
}

listener {
    timeout = 1000
    on-timeout = qs ipc call lock lock
}
