general {
    before_sleep_cmd = loginctl lock-session && solaar config "MX Mechanical Mini" backlight Disabled
    lock_cmd = hyprlock
    unlock_cmd = solaar config "MX Mechanical Mini" backlight Enabled
}
listener {
    timeout = 300
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })' && solaar config "MX Mechanical Mini" backlight Disabled
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && solaar config "MX Mechanical Mini" backlight Enabled
}
listener {
    timeout = 1000
    on-timeout = hyprlock
}
